export const GET_USER = 'GET_USER'
export const OPEN_FORM = 'OPEN_FORM'
export const CREATE_PROFILE = 'CREATE_PROFILE'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const PAGINATE = 'PAGINATE'
export const CURRENT_PAGE = 'CURRENT_PAGE'
